Database health-check, authorization with github and routes
Programmers-Only-Group/auth pull request #4
Opened 2020-08-21 13:31 UTC by KacperMalachowski

I changed the name of register endpoint compared to documentation to /login/callback because of that name better describes this endpoint.

2020-08-21 13:44 UTC, hayuna commented on src/config/development.js
> +    port: process.env.PORT | 3000,
<img width="203" alt="Screenshot 2020-08-21 at 15 43 12" src="https://user-images.githubusercontent.com/19636010/90897166-0890ef00-e3c5-11ea-9122-c346a89be33d.png">
Is this expected value? I think you missed or operator with bitwise operator

2020-08-21 13:44 UTC, hayuna commented on src/config/development.js
> +    callbackURL: "https://127.0.0.1/login/callback"
Can we store callback into .env?

2020-08-21 13:45 UTC, hayuna commented on src/controllers/AuthController.js
> +  redirectedUser: (req, res) => {
This is action unfinished. Should be named like `redirectUser`

2020-08-21 13:47 UTC, hayuna commented on src/controllers/HealthCheckController.js
> +    switch (mongoose.connection.readyState) {
Cant we just return this status?

2020-08-21 13:48 UTC, hayuna commented on src/models/User.js
> +  id: {
mongo generate their own id named `_id` and this is unique by default. I think, we can remove this field

2020-08-21 13:51 UTC, hayuna requested changes
This PR looks chaotic. Please talk with your PM about some convention in naming commits, naming branches and naming pull requests.

2020-08-21 13:51 UTC, hayuna commented
@bwieckow If we need to change 15 files to finish task, it looks like this task should be split to lower ones.

2020-08-21 19:44 UTC, Przemocny requested changes
3/10 imo, to fix

2020-08-21 19:44 UTC, Przemocny commented on src/config/development.js
> +    callbackURL: "https://127.0.0.1/login/callback"
it should be from process.env too

2020-08-21 19:44 UTC, Przemocny commented on src/controllers/AuthController.js
> +  redirectedUser: (req, res) => {
this action has not suitable name - it isnt redirectUser, its more like redirectToIndexWithUser for me

2020-08-21 19:44 UTC, Przemocny commented on src/controllers/HealthCheckController.js
> +    switch (mongoose.connection.readyState) {
this.getServiceStatus should return { isConnected, numericStatus, msg } to have all informations about status

2020-08-21 19:44 UTC, Przemocny commented on src/index.js
>  const bodyParser = require('body-parser');
bodyparser exist in express

app.use(express.json()) - .urlencoded is probably there too

2020-08-21 19:44 UTC, Przemocny commented on src/index.js
>  mongo.connect(config.mongo.connectionString, config.mongo.options);
from here this is onInit(app=express()){} function, down to the app.listen

2020-08-21 19:44 UTC, Przemocny commented on src/routes/auth.js
> +router.get('/', passport.authenticate('github'));
/ should be first

/callback should be second route

2020-08-21 19:44 UTC, Przemocny commented on src/config/passport.js
> +const passport = require('passport');
Why env doesnt have imports and exports ? 
and why not typescript ?

probably matching config of env is here https://github.com/Przemocny/ts_env_scripts

2020-08-21 19:44 UTC, Przemocny commented on src/models/User.js
> +UserSchema.statics.findOneOrCreate = function (accessToken, profile, cb)  {
this should be async/await promise, not callback based method

2020-08-21 20:11 UTC, hayuna commented on src/index.js
>  const bodyParser = require('body-parser');
>>app.use(express.json()) - .urlencoded is probably there too

Correct

2020-08-21 20:14 UTC, hayuna requested changes
Comments above

2020-08-23 07:56 UTC, KacperMalachowski commented on src/config/development.js
> +    port: process.env.PORT | 3000,
Yeah, I missed or operator with bitwise operator, fixed now.

2020-08-23 07:58 UTC, KacperMalachowski commented on src/config/development.js
> +    callbackURL: "https://127.0.0.1/login/callback"
Ok, I added dotenv package and configure it in src/config/index.js and I added example .env file to repository.

2020-08-23 07:59 UTC, KacperMalachowski commented on src/controllers/AuthController.js
> +  redirectedUser: (req, res) => {
Auth controller and redirectedUser replaced with buil-in passport.js redirect option.

2020-08-23 08:03 UTC, KacperMalachowski commented on src/controllers/HealthCheckController.js
> +    switch (mongoose.connection.readyState) {
Added more informative object with isConnected (bool for DB) or isReady (bool for service) and numeric status and message for both DB and Service.
Current structure:
`status {
  database {
     isConnected: bool,
     status: integer,
     message: string
  },
  service {
     isReady: bool,
     status: integer,
     message: string
  }
}`

2020-08-23 08:06 UTC, KacperMalachowski commented on src/models/User.js
> +  id: {
This is id  from github, I renamed it to githubId now. We use it to check if user already exists in our database.

2020-08-23 08:07 UTC, KacperMalachowski commented on src/models/User.js
> +UserSchema.statics.findOneOrCreate = function (accessToken, profile, cb)  {
Removed callback and convert to async/await based.

2020-08-23 08:11 UTC, KacperMalachowski commented
isReady function created for feature better service health check (which will be using more metrics than DB connection), but now would be replaced with simple invoke isCOnnected

2020-09-01 16:51 UTC, hayuna commented on .eslintrc
> +{
You can use our config if you have some problems

2020-09-07 17:47 UTC, closed without merging